luncheon/luncheon/urls.py
"""luncheon URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
"""
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('restaurant.urls')),
    url(r'^admin/', admin.site.urls),
]

luncheon/restaurant/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.urlpatterns import format_suffix_patterns

from . import views


app_name = 'restaurant'
urlpatterns = [
        url(r'^$', views.index, name='index'),
        url(r'^register/$', views.register, name='register'),
        url(r'^login/$', views.user_login, name='login'),
        url(r'^logout/$', views.user_logout, name='logout'),
        url(r'^list/$', views.restaurant_list, name='restaurant_list'),
        url(
            r'^restaurant/(?P<pk>\d+)$',
            views.restaurant_detail,
            name='restaurant_detail'
            ),
        url(
            r'^restaurant/(?P<pk>\d+)/review$',
            views.restaurant_review,
            name='restaurant_review'
            ),
        url(r'^add/$', views.restaurant_add, name='restaurant_add'),
        # API urls
        url(r'^api/v1/city/$', views.CityList.as_view(), name='city_api'),
        ]

urlpatterns = format_suffix_patterns(urlpatterns)

if settings.DEBUG:
    urlpatterns += static(
            settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT)

luncheon/restaurant/models.py
from django.db import models
from django.db.models import Avg
from django.contrib.auth.models import User


class TimeStampedModel(models.Model):
    """An abstract base class model that provides self-updating
    ``created`` and ``modified`` fields.
    """
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Country(models.Model):
    """Stores Countries from around the world."""
    name = models.CharField(
            "Country",
            max_length=50,
            )

    class Meta:
        verbose_name = 'Country'
        verbose_name_plural = 'Countries'

    def __str__(self):
        return self.name


class State(models.Model):
    """Stores State names from around the world."""
    name = models.CharField(
            "State",
            max_length=50,
            )
    country = models.ForeignKey(
            'Country',
            on_delete=models.CASCADE,
            )

    def __str__(self):
        return self.name


class City(models.Model):
    """Stores City names from around the world."""
    name = models.CharField(
            "City",
            max_length=50,
            )
    state = models.ForeignKey(
            'State',
            on_delete=models.CASCADE,
            )

    class Meta:
        verbose_name = 'City'
        verbose_name_plural = 'Cities'

    def __str__(self):
        return self.name


class Restaurant(TimeStampedModel):
    """Stores restaurant information."""
    name = models.CharField(max_length=100,)
    image = models.ImageField(upload_to='restaurant_image')
    phone = models.CharField(max_length=20,)
    email = models.EmailField(blank=True)
    website = models.URLField(blank=True)
    open_time = models.TimeField(blank=True, null=True)
    close_time = models.TimeField(blank=True, null=True)
    address = models.CharField(max_length=255,)
    city = models.ForeignKey(
            'City',
            on_delete=models.CASCADE,
            )

    def average_rating(self):
        """Return the average rating for a restaurant."""
        restaurant_reviews = self.review_set.all()
        restaurant_average_rating = restaurant_reviews.aggregate(
                Avg('rating'))['rating__avg']
        return restaurant_average_rating

    def available_food_categories(self):
        """Returns all the food categories for a restaurant."""
        restaurant_category = self.menuitem_set.all()
        categories = ', '.join(
                set([c.category.name for c in restaurant_category])
                )
        return categories

    def __str__(self):
        return self.name


class FoodCategory(TimeStampedModel):
    """Stores categories of food."""
    name = models.CharField(
            "Category",
            max_length=255,
            )

    class Meta:
        verbose_name = 'Food Category'
        verbose_name_plural = 'Food Categories'

    def __str__(self):
        return self.name


class MenuItem(TimeStampedModel):
    """Stores food items served by restaurants."""
    name = models.CharField(max_length=150,)
    price = models.DecimalField(
            max_digits=10,
            decimal_places=2,
            )
    category = models.ForeignKey(
            'FoodCategory',
            on_delete=models.CASCADE
            )
    restaurant = models.ForeignKey(
            'Restaurant',
            on_delete=models.CASCADE
            )

    def __str__(self):
        return self.name


class UserProfile(TimeStampedModel):
    """Stores User information."""
    user = models.OneToOneField(User, related_name='profile')
    address = models.CharField(
            blank=True,
            help_text="It would help us give better restaurant\
            recommendations.",
            max_length=255,
            )
    city = models.ForeignKey(
            'City',
            on_delete=models.CASCADE,
            blank=True,
            null=True
            )
    website = models.URLField(blank=True)
    picture = models.ImageField(
            upload_to='profile_images',
            blank=True,
            )
    phone = models.CharField(
            max_length=15,
            blank=True)
    bio = models.TextField(
            max_length=170,
            blank=True
            )

    def __str__(self):
        return self.user.username


class Review(TimeStampedModel):
    """Stores restaurant review."""
    RATING_CHOICES = (
            (1, '1'),
            (2, '2'),
            (3, '3'),
            (4, '4'),
            (5, '5'),
            )
    rating = models.IntegerField(
            choices=RATING_CHOICES,
            )
    overall_rating = models.BooleanField(
            verbose_name='Like',
            )
    review_text = models.TextField(
            verbose_name='Review',
            )
    restaurant = models.ForeignKey(
            'Restaurant',
            on_delete=models.CASCADE,
            )
    user = models.ForeignKey(
            User,
            on_delete=models.CASCADE
            )

    class Meta:
        unique_together = ('restaurant', 'user')

    def __str__(self):
        return self.review_text


class Comment(TimeStampedModel):
    """Stores comments on reviews by user."""
    comment = models.TextField()
    review = models.ForeignKey(
            'Review',
            on_delete=models.CASCADE
            )
    user = models.ForeignKey(
            User,
            on_delete=models.CASCADE
            )

    def __str__(self):
        return self.comment


class Visit(models.Model):
    """Stores if user has visited a restaurant or not.
    If restaurant_id and user_id are present then
    the user has visited otherwise not.
    """
    restaurant = models.ForeignKey(
            'Restaurant',
            on_delete=models.CASCADE
            )
    user = models.ForeignKey(
            User,
            on_delete=models.CASCADE
            )

luncheon/restaurant/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db import IntegrityError
from django.db.models import Q, Avg

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status

from .serializers import CitySerializer
from .models import Restaurant, City
from .forms import (
        UserForm, UserProfileForm,
        RestaurantAddForm, ReviewForm,
        CommentForm
        )


def register(request):
    """Handles user registration."""

    if request.method == 'POST':
        # Grab information from the raw form - both UserForm and
        # and UserProfileForm
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        # If the two forms are valid, process further
        if user_form.is_valid() and profile_form.is_valid():
            # Save the user form data to the database.
            user = user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()

            # Now sort out the UserProfile instance.
            # Since we need to set the user attribute ourselves, we set
            # commit=False.
            #city = get_object_or_404(
            #        City,
            #        pk=profile_form.cleaned_data.get('city')
            #        )
            profile = profile_form.save(commit=False)
            profile.user = user
            #profile.city = city

            # Process the profile picture, if present
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            # Save the UserProfile model instance.
            profile.save()

            # Set registration to True to tell the template registration was
            # successful.
            messages.success(
                    request,
                    'Your account has been successfully created.'
                    )

        else:
            print(user_form.errors, profile_form.errors)
            messages.warning(
                    request,
                    'Please correct the error(s) and submit again.'
                    )
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(
            request,
            'restaurant/register.html',
            {
                'user_form': user_form,
                'profile_form': profile_form,
                }
            )


def user_login(request):
    """Handles login."""
    print(request.POST)
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Using Django's method to authenticate user.
        # If username/password combination is valid - a User object
        # is retured.
        user = authenticate(username=username, password=password)

        # If we have a user object then the credentials were correct
        # else None is returned
        if user:
            # Checking if account is active
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/')
            else:
                messages.warning(
                        request,
                        'Your account has been disabled'
                        )
                return render(request, 'restaurant/login.html', {})
        else:
            messages.warning(
                    request,
                    'Invalid credentials. Try again.'
                    )
            return render(request, 'restaurant/login.html', {})
    else:
        return render(request, 'restaurant/login.html', {})


@login_required
def user_logout(request):
    """Handles logout."""
    logout(request)

    return HttpResponseRedirect('/')


def index(request):
    """Lists restaurants based on user's current location."""
    # Get the latest 3 restaurant
    restaurant_list = Restaurant.objects.all().order_by('-created')[:3]
    cities = City.objects.select_related().filter(
            state__country__name='India'
            )
    return render(
            request, 'restaurant/index.html',
            {
                'restaurants': restaurant_list,
                'cities': cities,
                }
            )


def restaurant_list(request):
    """Lists all restaurants or based on user search criteria."""
    restaurant_list = Restaurant.objects.all()
    context = {}
    query = request.GET.get('query')
    city = request.GET.get('city', None)
    cities = City.objects.select_related().all()
    # If we get a blank query, we show all restaurants in a city
    if city and not query:
        city_queryset = cities.get(id=city)
        context.update({'city': city_queryset.name})
        restaurant_list = restaurant_list.filter(
                Q(city=city) |
                Q(address__icontains=city_queryset.name)
                )
    # If we get a query then we show restaurants which contains the
    # keyword and are in the searched city.
    if query:
        restaurant_list = restaurant_list.filter(
                Q(city=city) &
                Q(name__icontains=query) |
                Q(menuitem__name__icontains=query) |
                Q(menuitem__category__name__icontains=query)
                ).distinct()
    context.update(
            {
                'restaurant_list': restaurant_list,
                'cities': cities,
                'query': query
                }
            )
    return render(
            request,
            'restaurant/restaurant_list.html',
            context
            )


@login_required
def restaurant_add(request):
    """Handles the restaurant add feature."""
    if request.method == 'POST':
        restaurant_add_form = RestaurantAddForm(data=request.POST)

        # Check if the form is valid
        if restaurant_add_form.is_valid():
            restaurant_add_form.save()
            return HttpResponseRedirect('/')
        else:
            print(restaurant_add_form.errors)
    else:
        restaurant_add_form = RestaurantAddForm()

    return render(
            request,
            'restaurant/restaurant_add.html',
            {'restaurant_add_form': restaurant_add_form}
            )


def restaurant_detail(request, pk):
    """Handles details page of restaurant."""
    restaurant = get_object_or_404(Restaurant.objects.select_related(), pk=pk)
    restaurant_menu = restaurant.menuitem_set.all()
    restaurant_reviews = restaurant.review_set.all()
    restaurant_average_rating = restaurant_reviews.aggregate(
            Avg('rating'))['rating__avg']
    print(restaurant, restaurant_menu, restaurant_reviews)
    context = {
            'restaurant': restaurant,
            'restaurant_menu': restaurant_menu,
            'restaurant_reviews': restaurant_reviews,
            'restaurant_average_rating': restaurant_average_rating
            }
    return render(
            request,
            'restaurant/restaurant_detail.html',
            context
            )


def restaurant_review(request, pk):
    """Handles reviews page of restaurant."""
    # Set save to True if registratio is succesful
    review_save = False
    restaurant = get_object_or_404(Restaurant.objects.select_related(), pk=pk)
    restaurant_reviews = restaurant.review_set.all()
    restaurant_average_rating = restaurant_reviews.aggregate(
            Avg('rating'))['rating__avg']
    if request.method == 'POST':
        review_form = ReviewForm(data=request.POST)
        if review_form.is_valid():
            try:
                form = review_form.save(commit=False)
                form.user = request.user
                form.restaurant = restaurant
                form.save()
                messages.success(
                        request,
                        'You are review has been adedd succesful'
                        )
            except IntegrityError:
                messages.warning(
                        request,
                        'You can only add one review per restaurant.'
                        )
                pass
        else:
            print(review_form.errors)
    else:
        review_form = ReviewForm()
    context = {
            'restaurant': restaurant,
            'restaurant_reviews': restaurant_reviews,
            'restaurant_average_rating': restaurant_average_rating,
            'review_form': review_form,
            'review_save': review_save,
            }
    return render(
            request,
            'restaurant/restaurant_review.html',
            context
            )


# API views
class CityList(APIView):
    """Returns city based on query string."""

    def get(self, request):
        # Look for the query string term
        term = request.GET.get('term')
        if term:
            cities = City.objects.filter(name__icontains=term)
            serializer = CitySerializer(cities, many=True)
            return Response(serializer.data)
        else:
            return Response([])

luncheon/restaurant/templates/restaurant/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    {% block meta_tags %}
    {% endblock %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'restaurant/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'restaurant/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'restaurant/css/animsition.min.css' %}" rel="stylesheet">
    <link href="{% static 'restaurant/css/animate.css' %}" rel="stylesheet">
    {% block stylesheet %}{% endblock %}
    <!-- Custom styles for this template -->
    <link href="{% static 'restaurant/css/style.css' %}" rel="stylesheet"> </head>

<body {% block body_class %}{% endblock %}>
    <div class="site-wrapper animsition" data-animsition-in="fade-in" data-animsition-out="fade-out">
        <!--header starts-->
        <header id="header" class="header-scroll top-header headrom">
            <!-- .navbar -->
            <nav class="navbar navbar-dark">
                <div class="container">
                    <button class="navbar-toggler hidden-lg-up" type="button" data-toggle="collapse" data-target="#mainNavbarCollapse">&#9776;</button>
                    <a class="navbar-brand" href="index.html"> <img class="img-rounded" src="images/food-picky-logo.png" alt=""> </a>
                    <div class="collapse navbar-toggleable-md  float-lg-right" id="mainNavbarCollapse">
                        <ul class="nav navbar-nav">
                            <li class="nav-item"> <a class="nav-link active" href="{% url 'restaurant:index' %}">Home <span class="sr-only">(current)</span></a> </li>
                            <li class="nav-item dropdown"> <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="{% url 'restaurant:restaurant_list' %}" role="button" aria-haspopup="true" aria-expanded="false">Restaurants</a>
                                <div class="dropdown-menu"> <a class="dropdown-item" href="{% url 'restaurant:restaurant_add' %}">Add Restaurant</a> <a class="dropdown-item" href="{% url 'restaurant:restaurant_list' %}">Search Restaurant</a></div>
                            </li>
                            <li class="nav-item dropdown"> <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="{% url 'restaurant:register' %}" role="button" aria-haspopup="true" aria-expanded="false">Register</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="{% url 'restaurant:login' %}">Login</a>
                                    <a class="dropdown-item" href="{% url 'restaurant:register' %}">Register</a>
                                    <a class="dropdown-item" href="{% url 'restaurant:logout' %}">Logout</a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- /.navbar -->
        </header>
        {% block content %}{% endblock %}
        <!-- start: FOOTER -->
        <footer class="footer">
            <div class="container">
                <p class="text-center">Copyright 2017. Luncheon</p>
            </div>
        </footer>
        <!-- end:Footer -->
    </div>
    <!--/end:Site wrapper -->
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <script src="{% static 'restaurant/js/jquery.min.js' %}"></script>
    <script src="{% static 'restaurant/js/tether.min.js' %}"></script>
    <script src="{% static 'restaurant/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'restaurant/js/animsition.min.js' %}"></script>
    <script src="{% static 'restaurant/js/bootstrap-slider.min.js' %}"></script>
    <script src="{% static 'restaurant/js/jquery.isotope.min.js' %}"></script>
    <script src="{% static 'restaurant/js/headroom.js' %}"></script>
    <script src="{% static 'restaurant/js/foodpicky.min.js' %}"></script>
    {% block javascript %}
    {% endblock %}
</body>

</html>

luncheon/restaurant/templates/restaurant/index.html
{% extends 'restaurant/base.html' %}
{% load static %}
{% block meta_tags %}
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="#">
    <title>Luncheon - Helping you discover great food</title>
{% endblock %}
{% block stylesheet %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-theme/0.1.0-beta.10/select2-bootstrap.min.css" rel="stylesheet" />
<style>
  .select2-container--bootstrap .select2-selection--single{
    height: 51px;
    font-size: 18px;
    padding: 10px 24px 6px 12px;
  }

</style>
{% endblock %}
{% block body_class %}class="home"{% endblock %}
{% block content %}
        <!-- banner part starts -->
        <section class="hero bg-image" data-image-src="{% static 'restaurant/images/index_banner.jpg' %}">
            <div class="hero-inner">
                <div class="container text-center hero-text font-white">
                    <h1>Find great restaurants and more </h1>
                    <h5 class="font-white space-xs">Find restaurants, specials, and coupons for free</h5>
                    <div class="banner-form">
                        <form class="form-inline" method="GET" action="{% url 'restaurant:restaurant_list' %}">
                                <div class="form-group">
                                <label class="sr-only" for="city">I would like to eat....</label>
                                <div class="form-group">
                                  <select name='city' id="id_city" class="form-control form-control-lg" style="width: 100%;">
                                  </select>
                                </div>
                                <label class="sr-only" for="query">I would like to eat....</label>
                                <div class="form-group">
                                    <input type="text" class="form-control form-control-lg" id="id_query" name="query" placeholder="I would like to eat...."> </div>
                            </div>
                            <button type="submit" class="btn theme-btn btn-lg">Search food</button>
                        </form>
                    </div>
                </div>
            </div>
            <!--end:Hero inner -->
        </section>
        <!-- banner part ends -->
        <!-- location match part starts -->
        <div class="location-match text-xs-center">
            <div class="container"> <span>356 restaurants matched your location: <span class="primary-color">New Delhi</span> </span>
            </div>
        </div>
        <!-- location match part ends -->
        <!-- Popular block starts -->
        <section class="popular">
            <div class="container">
                <div class="title text-xs-center m-b-30">
                    <h2>Popular This Month In Your City</h2>
                    <p class="lead">The easiest way to your favourite food</p>
                </div>
                <div class="row">
                    <!-- Each popular food item starts -->
                    {% for restaurant in restaurants %}
                    <div class="col-xs-12 col-sm-6 col-md-4 food-item">
                        <div class="food-item-wrap">
                        {% if restaurant.image %}
                            <div class="figure-wrap bg-image" data-image-src="{{ MEDIA_URL }}{{ restaurant.image }}">
                        {% else %}
                            <div class="figure-wrap bg-image" data-image-src="http://placehold.it/380x210">
                        {% endif %}
                                <div class="distance"><i class="fa fa-pin"></i>1240m</div>
                                <div class="rating pull-left"> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star-o"></i> </div>
                                <div class="review pull-right"><a href="#">{{ restaurant.review_set.count }} reviews</a> </div>
                            </div>
                            <div class="content">
                                <h5><a href="{% url 'restaurant:restaurant_detail' restaurant.id %}">{{ restaurant.name }}</a></h5>
                                <div class="product-name">{{ restaurant.available_food_categories }}</div>
                                <div class="price-btn-block"> <span class="price">{{ restaurant.average_rating }}/5</span> <a href="{% url 'restaurant:restaurant_detail' restaurant.id %}" class="btn theme-btn-dash pull-right">View Now</a> </div>
                            </div>
                            <!-- <div class="restaurant-block">
                                <div class="left">
                                    <a class="pull-left" href="profile.html"> <img src="http://placehold.it/50x46" alt="Restaurant logo" /> </a>
                                    <div class="pull-left right-text"> <a href="#">Chicken Restaurant</a> <span>68 5th Avenue New York</span> </div>
                                </div>
                                <div class="right-like-part pull-right"> <i class="fa fa-heart-o"></i> <span>48</span> </div>
                            </div> -->
                        </div>
                    </div>
                    {% empty %}
                      <p>There are no restaurants in the system.</p>
                    {% endfor %}
            </div>
        </section>
        <!-- Popular block ends -->
        <!-- Featured restaurants starts -->
        <section class="featured-restaurants">
            <div class="container">
                <!-- add restaurant starts -->
                <section class="add-restaurants">
                    <div class="container">
                        <div class="row">
                            <div class="col-xs-12 col-sm-3 add-title">
                                <h4>Add Your Restaurant</h4> </div>
                            <div class="col-xs-12 col-sm-5 join-text">
                                <p>Join the thousands of other restaurants who benefit from having their menus on <a href="#"><strong> Luncheon</strong></a> </p>
                            </div>
                            <div class="col-xs-12 col-sm-4 join-btn text-xs-right"><a href="{% url 'restaurant:restaurant_add' %}" class="btn theme-btn btn-lg">I‘m restaurant</a> </div>
                        </div>
                    </div>
                </section>
                <!-- add restaurant ends -->
            </div>
        </section>
        <!-- Featured restaurants ends -->
    <!--/end:Site wrapper -->
{% endblock %}
{% block javascript %}
 <!-- Select2 plugin -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.full.js"></script>

<script>
      $(function(){
        // Select2 Initialization
        $('#id_city').select2({
            theme: "bootstrap",
            ajax: {
            url: "{% url 'restaurant:city_api' %}",
            dataType: 'json',
            processResults: function (data) {
                var data = $.map(data, function (obj) {
                obj.text = obj.text || obj.name; // replace name with the property used for the text
                return obj;
            });
            // Tranforms the top-level key of the response object from 'items' to 'results'
            return {
                results: data
            };
        }
    },
    placeholder: 'Select your city',
    minimumInputLength: 3,
});
       
      });
    </script>
{% endblock %}

luncheon/restaurant/templates/restaurant/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}